logging:
  config: /etc/simple/logback-spring.xml
#小程序及公众号配置
wechat :
  xcx :
    meetinglive :
      appId: wx23687b634498f224
      appSecret: bf1a4693c9bae08e0da1b2025864582a
      jscode2session: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
      accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
      getwxacodeunlimit: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=ACCESS_TOKEN
  public:
    publicAppId: "wx84f80fb39e1b266b"
    publicSecret: "6ef821b6d6de49b1210e0a0601fc1493"
    userAauth2: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE&connect_redirect=1#wechat_redirect
    oauthAccessToken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
    oauthUserInfo: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN

#redis参数配置
redis:
  hostName: 47.101.223.234
  redisport: 6379
  passWord: meetinglive
  maxActive: 800
  maxIdle: 100
  maxWait: 1000
  testOnBorrow: true
spring:
  redis:
    database: 0
    host: 47.101.223.234
    port: 6379
    password: meetinglive

server:
  servlet:
    context-path: /simple/account