# application.yml

spring:
  profiles:
    active: dev
  application:
    name: account-service
  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}
  redis:
    database: 0
    host: images.e-healthcare.net
    port: 6379
    password: meetinglive

simple:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-server-server:80}


server:
  servlet:
    context-path: /simple/account