spring:
  datasource:
    url: jdbc:mysql://db.koudaibook.com:30006/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: MySQL5Dialect

server:
  port: 8888
  servlet:
    context-path: /simple
simple:
  domainName: koudaibook.com
  email-service-endpoint: http://localhost:8088
  common:
    sentry-dsn: https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087
management:
  endpoints:
    web:
      exposure:
        include: "*"

#小程序及公众号配置
wechat :
  xcx :
    meetinglive :
      appId: wx23687b634498f224
      appSecret: bf1a4693c9bae08e0da1b2025864582a
      jscode2session: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
      accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
      getwxacodeunlimit: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=ACCESS_TOKEN
  public:
    publicAppId: "wx84f80fb39e1b266b"
    publicSecret: "6ef821b6d6de49b1210e0a0601fc1493"
    userAauth2: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE&connect_redirect=1#wechat_redirect
    oauthAccessToken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
    oauthUserInfo: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN


